//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentData
    {
        public int Id { get; set; }
        public string Student { get; set; }
        public int LanguageArts { get; set; }
        public int Science { get; set; }
        public int SocialStudies { get; set; }
        public int Maths { get; set; }
    }
}
